#!/usr/bin/env bash

BLOB="https://github.com/MartinRosenberg/Mac-Setup/blob/master"

# Copy dotfiles
cd ~
curl --location --remote-name-all "${BLOB}/{.bash_profile,.gitconfig,.vimrc,.zshrc}"

# Install Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash

# Install almost everything else
curl -o- "${BLOB}/.Brewfile" | brew bundle install --verbose > brew_bundle.log
