#!/usr/bin/env bash

################################################################################
### Declare things
################################################################################

GH_RAW="https://raw.githubusercontent.com"
BLOB="${GH_RAW}/MartinRosenberg/Mac-Setup/master"

################################################################################
### Do things
################################################################################

# Copy dotfiles
cd ~
curl --location --remote-name-all "${BLOB}/{.bash_profile,.gitconfig,.vimrc,.zshrc}"

# Can't use .zshrc yet
source .bash_profile

# Install Homebrew
if ! command -v brew > /dev/null; then
	/usr/bin/ruby -e "$( curl -fsSL "${GH_RAW}/Homebrew/install/master/install" )"
fi

# Install Brewfile
curl -o- "${BLOB}/Brewfile" | brew bundle install --verbose

# Install nvm
if ! command -v nvm > /dev/null; then
	curl -o- "${GH_RAW}/nvm-sh/nvm/v0.35.2/install.sh" | bash
fi

# Install iTerm2 shell integration
if ! command -v it2check > /dev/null; then
	curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash
fi

# Show full path in Finder
defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES && killall Finder
